---
title: "Thesis Supervision"
author: 'Lachlan Deer'
date:  "Last Updated: `r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

# Master's Theses

## 2019

* Dynamic Pricing Under Demand Uncertainty

## 2018

* The Impact of Social Media Generated Word of Mouth on the Demand for Movies
* The Impact of Word of Mouth on the Demand for Experience Goods: An Empirical Analysis

## 2015

* Product Bundling with Mutlidimensional Consumer Search

# Bachelor's Theses

## 2018

* Nested Logit Demand Estimation with Aggregate Market Shares
* Does Advertising Respond to Consumer Sentiment? Evidence from the Film Industry
* An Emprical Analysis of Pre-release Word of Mouth on New Product Performance
* Social Spillovers and Consumer Learning in the Movie Industry


## 2016

* How does Television Effect Family Outcomes?
* Advertising Strategies in Oligopolstic Markets: When and Where to Advertise

## 2015

* The Economics of Net Neutrality: An Application to the U.S. Policy Debate
* Pulsing Advertising Content: An Empirical Analysis of the Hungarian Mobile Market